packages: [ "/apps/*", "/components/*", "integrations/*" ]
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  nx: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true
minimumReleaseAge: 2880
